### ISSUE TITLE
S2 feedback and stuff to do

### ISSUE THREAD

**Issue by nemaara** [DivitSingh/The_Rise_Of_Wesnoth_Rework#1]
List of feedback so I don't forget later:

1. Why does Eldaric run so far when you attack the Wesfolk? Shouldn't he just take over their camp or set something up close by to hold the orcs where they are? It looks weird when he runs so far south and you're lagging behind.
2. Need to add/touch up some dialogue.
3. Can we narrow the mountain path more? Makes it look even longer.
4. Add a second wolf side to pincer from both sides of the mountains, but make each one weaker than the current one.

**Comment by ghost** [comment]
Thanks for the feedback, here is what I have done to address it.
1. I've shifted Eldaric to the Wesfolk camp. To account for the situation where you decline the Wesfolk, I've added a cutscene where Eldaric kills the Wesfolk currently occupying the camp so he can recruit normally the next turn.
2. For the dialogue, I haven't been editing it too much to avoid translation issues. Can I do more than just re-purpose existing lines to different events? If so, would a more formal tone be suited to this campaign, since I see we use a lot of contractions, and colloquial language later down the line. Basically, could I shift the tone to be more like the current dialogue in TSG?
3. Path is narrower now, and tapers down in the end to be a 1-hex valley.
4. I've created a second leader with an encampment on the opposite section of the valley. Both Goblin Pillagers are shared side with common resources.

**Comment by Mirion147** [comment]
I don't mind going over the dialog, if the powers at be are okay with that. I just didn't want to go over it until there was a clear understanding of what was going on and why

**Comment by mavpii** [comment]
Well, I played the updated version of the second scenario and I can say that I couldn't win, I failed many and many times. The orcs' gold is fine, they now really feel like a real threat that cannot be stopped(and not like a bunch of thugs who are easy to defeat, as it was before). 

But as for the goblins, I think everything is very bad. Given that there are now two of their leaders, it was impossible for me to get through their units after turn 10.  Their income grew too much and I just couldn't do anything against them, even having several second-level units.

I suggest not to raise the goblins' income or do it much later, at least for the story reasons. As I understand it correctly, these goblins are just scouts who just happened to be where they are thanks to the fast wolves. And since the army of orcs comes from the north, it's a little strange that the forces in the south are also receiving reinforcements.

And also about the new location of the King's last stand. This is not a bad idea, as he occupies a already built castle and fights the advancing orcs, not the goblin scouts (it often happened that my troops had not yet left the valley, and the King was almost dead). 

But on other hand the player loses the opportunity to quickly leave the starting castle and recruit more units on the way. Because of this, Haldric is delayed in the starting castle for 2-3 turns, and then you can only leave the valley by sacrificing several of your soldiers. 

Btw, here is my replay of the most successful attempt.
[TRoW Re-Farewell to Stormvale повтор 20240417-212408.gz](https://github.com/Gweddeoran/The_Rise_Of_Wesnoth_Rework/files/15016576/TRoW.Re-Farewell.to.Stormvale.20240417-212408.gz)
